{{- if source_only ~}}
using System;
using System.Diagnostics.CodeAnalysis;

#if !MYPACKAGE_COMPILE

// <autogenerated />
#pragma warning disable
#endif

#nullable disable

namespace MyPackage
{
{{~ else ~}}
namespace MyPackage;

{{~ end -}}

{{~ if source_only ~}}
[global::System.Diagnostics.DebuggerNonUserCode]
[global::Microsoft.CodeAnalysis.Embedded]
{{~ end ~}}
public class MyClass
{
}
{{~ if source_only ~}}
}

// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#pragma warning disable
namespace Microsoft.CodeAnalysis
{
    /// <summary>
    /// A special attribute recognized by Roslyn, that marks a type as "embedded", meaning it won't ever be visible from other assemblies.
    /// </summary>
    [AttributeUsage(AttributeTargets.All)]
    [ExcludeFromCodeCoverage]
    internal sealed class EmbeddedAttribute : Attribute
    {
    }
}
#pragma warning restore
{{~ end ~}}
